site_name: Legacy Modding Wiki by nea89
site_url: https://moddev.nea.moe/
site_description: |
  My wiki for 1.8.9 Forge modding beginners and experts alike.
repo_name: nea89o/ModDevWiki
repo_url: https://github.com/nea89o/ModDevWiki
edit_uri: blob/master/docs



nav:
  - index.md
  - ide-setup.md
  - events.md
  - commands.md
  - screens.md
  - inventories.md
  - vanilla.md
  - Mixins:
    - mixins/index.md
    - mixins/accessors.md
    - mixins/adding-fields.md
    - mixins/simple-injects.md
  - hotswap.md
  - tweakers.md
  - https.md


validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - content.action.edit
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode


plugins:
  - search
  - social
  - material-plausible
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra:
  analytics:
    provider: plausible
    domain: moddev.nea.moe
    src: "https://pla.nea.moe/js/plausible.js"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/shared_links.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
